# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54c26e52da51b3259b7011a1240ec10d1261024ab14c63e8cfdfbd238aedb2879b51be16c90f194a8257defc5a10c38cdead0e1a952e9b98379ab7bdaed8d7fd

test:
  secret_key_base: 9ecf626ee9096aff6027b6b86b039002d7d21ffc9d9d13ffd8e18798e2745ed638bad205e7f15834457a4521a842ea93a0bbb17f3700e34544fe067071a4567e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
